<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>EmptyProject</artifactId>
    <version>1.0-SNAPSHOT</version>

<!--    <developers>-->
<!--        <developer>-->
<!--            <id>john.doe</id>-->
<!--            <name>John Doe</name>-->
<!--            <email>john.doe@example.com</email>-->
<!--            <url>http://www.example.com</url>-->
<!--            <organization>Example Corp</organization>-->
<!--            <organizationUrl>http://www.example.com</organizationUrl>-->
<!--            <roles>-->
<!--                <role>architect</role>-->
<!--                <role>developer</role>-->
<!--            </roles>-->
<!--            <timezone>+8</timezone>-->
<!--            <properties>-->
<!--                <picUrl>image/john_doe.png</picUrl>-->
<!--            </properties>-->
<!--        </developer>-->
<!--        <developer>-->
<!--            <id>jane.smith</id>-->
<!--            <name>Jane Smith</name>-->
<!--            <email>jane.smith@example.com</email>-->
<!--            <roles>-->
<!--                <role>tester</role>-->
<!--            </roles>-->
<!--        </developer>-->
<!--    </developers>-->

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.plugin</groupId>
                <artifactId>developers-info-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>print</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>